### ISSUE TITLE
[4.0.6] Build fails with UPNP too few arguments error

### ISSUE THREAD

**Issue by Here-Be-Saoirse** [transmission/transmission#7315]
### What is the issue?

The transmission daemon (version 4.0.6) fails to build under the following circumstances:

* Operating system: Solaris 10 1/13 s10s_u11wos_24a SPARC (SunOS 5.10 Generic_150400-59) (SUN4U)
* Compiler: GCC (9.5.0)
* Linker: GNU Binutils LD (2.43)
* Gnu Make version: 4.4
* CMAKE version: 3.31.1
* Configuration command: cmake -B build -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/FSYS/packages -DUSE_SYSTEM_MINIUPNPC=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=OFF

The build fails with the following error:

```
[ 36%] Building CXX object libtransmission/CMakeFiles/transmission.dir/port-forwarding-upnp.cc.o
/usr/src/build/progress/transmission-4.0.6/libtransmission/port-forwarding-upnp.cc: In function 'tr_port_forwarding_state tr_upnpPulse(tr_upnp*, tr_port, bool, bool, std::string)':
/usr/src/build/progress/transmission-4.0.6/libtransmission/port-forwarding-upnp.cc:278:111: error: too few arguments to function 'int UPNP_GetValidIGD(UPNPDev*, UPNPUrls*, IGDdatas*, char*, int, char*, int)'
  278 |         if (UPNP_GetValidIGD(devlist, &handle->urls, &handle->data, std::data(lanaddr), std::size(lanaddr) - 1) ==
      |                                                                                                               ^
In file included from /usr/src/build/progress/transmission-4.0.6/libtransmission/port-forwarding-upnp.cc:19:
/usr/src/build/progress/transmission-4.0.6/build/third-party/miniupnpc.bld/pfx/include/miniupnpc/miniupnpc.h:122:1: note: declared here
  122 | UPNP_GetValidIGD(struct UPNPDev * devlist,
      | ^~~~~~~~~~~~~~~~
make[2]: *** [libtransmission/CMakeFiles/transmission.dir/build.make:569: libtransmission/CMakeFiles/transmission.dir/port-forwarding-upnp.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:539: libtransmission/CMakeFiles/transmission.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

It makes little sense to us why such an error would occur, given that miniupnpc in that configuration is being built with Transmission, though for a sanity check, yes, it errors in the same way when using an external version of miniupnpc. Please advise on what to do next.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.6

**Comment by Here-Be-Saoirse** [comment]
Update: It seems to work fine with 2.2.6. The commit in miniupnpc that caused the build to now fail, which was also tested on Linux and it does, indeed, fail, is : https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f

**Comment by TasPats** [comment]
Debian Trixie up-to-date, use from repositories version 4.1.0~beta2, but there was strange things when transmission deletes previously downloaded files, if repeated download .torrent and don't select they now, try to build:
- download official 4.0.6, extract,
- follow instructions:
    mkdir build
    cd build
    $ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    $ make
get this error:
"transmission-4.0.6/libtransmission/port-forwarding-upnp.cc:278:29: error: too few arguments to function ‘int UPNP_GetValidIGD(UPNPDev*, UPNPUrls*, IGDdatas*, char*, int, char*, int)’
  278 |         if (UPNP_GetValidIGD(devlist, &handle->urls, &handle->data, std::data(lanaddr), std::size(lanaddr) - 1) =="

may be it is fixed in dev branch, may be it compiles if downgrade upnp to 2.2.6, but I think, that it is too difficult way to next-next-next man, as me

I think, that official download (latest) must compile without such.

but I try to **downgrade to miniupnpc-2.2.6** compile it, and now transmission 4.0.6 also compiles

great!
