### ISSUE TITLE
Requirements in Building-Transmission.md are out of date

### ISSUE THREAD

**Issue by grr** [transmission/transmission#8318]
According to [Building-Transmission.md](https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md) the requirements are:
* macOS 11.0 or newer
 * Xcode 12.5.1 or newer

My system satisfies these requirements:

    $ sw_vers -productVersion
    11.7.10

    $  xcodebuild -version
    Xcode 13.2.1
    Build version 13C100

The build process fails with the same error in multiple files:

    /tmp/src/transmission/libtransmission/api-compat.cc:11:10: fatal error: 'ranges' file not found
    #include <ranges>
            ^~~~~~~~

This appears to be an intentional design choice as referenced by this ticket: https://github.com/transmission/transmission/issues/5854#issuecomment-1660658169 . If so, the requirements are now out of date and need updating.

**Comment by grr** [comment]
> This appears to be an intentional design choice as referenced by this ticket: https://github.com/transmission/transmission/issues/5854#issuecomment-1660658169 . If so, the requirements are now out of date and need updating.

Turns out the offending change was made 5 days ago: https://github.com/transmission/transmission/commit/78e733e7bda462b7d3f6b8555174607ecd1fa724 . The parent builds fine for me.

**Comment by tearfur** [comment]
@ckerr Realistically speaking, some of us (including me) have no way to maintain the macOS build requirements because the GHA CI (which only goes back to macOS 15) is all we have to rely on.

IIRC the current macOS requirement for building the app is the same as `RECOMMENDED_MACOSX_DEPLOYMENT_TARGET`. Can we split them so that the build requirements are whatever the oldest CI available is, while `RECOMMENDED_MACOSX_DEPLOYMENT_TARGET` remains what it is now?

**Comment by ckerr** [comment]
@tearfur That sounds reasonable but I am not the best person to answer this -- I don't understand the implications. There are several people eg @livings124 @nevack @Coeur @fxcoudert who will have a more informed answer than me.

**Comment by Coeur** [comment]
While I understand the limitations of the GitHub Actions CI:
https://docs.github.com/en/actions/reference/runners/github-hosted-runners

My current strategy in general is to stick to what Apple supports under "Security fixes":
https://support.apple.com/en-us/100100

And as you can see, there was a Security patch yesterday for macOS 11.7.11, so @grr operating system should ideally be supported.

But that would mean watching closely the Xcode limitations at https://developer.apple.com/xcode/cpp/.
Since too few of us have the hardware/system to test such old setups, it's unfortunately not easily doable (unless, if you @grr start to make pull requests to offer compatibility?).

So in practice:
- We can support **running** on RECOMMENDED_MACOSX_DEPLOYMENT_TARGET (which is currently macOS 11).
- We can support **building** on what Github Actions supports (which is currently macOS 13).

But then again, while GHA supports macOS 13, it was showing as deprecated, so we bumped it to macOS 14-15: #7845 / ...

[edit]
Actually, I see conflicting informations from those two sites:
- https://docs.github.com/en/actions/reference/runners/github-hosted-runners says minimum is macos-13
- https://github.com/actions/runner-images/tree/main says minimum is macos-14

**Comment by Coeur** [comment]
Anyway, since I'm 100% sure that #8181 will not be reverted, I've made a PR to update the documentation requirements:
- #8338

The thing is: Transmission is currently an application, not a reusable framework or library, so it doesn't have higher requirements for compatibility than what GitHub Actions provides.
