### ISSUE TITLE
transmission 2.93 fails to build against libressl 2.4.4

### ISSUE THREAD

**Issue by thoradia** [transmission/transmission#486]
transmission 2.93 fails to build against libressl 2.4.4 with the following errors:
```
transmission-2.93/libtransmission/crypto-utils-openssl.c:304: error: undefined reference to 'DH_set0_pqg'
transmission-2.93/libtransmission/crypto-utils-openssl.c:338: error: undefined reference to 'DH_set_length'
transmission-2.93/libtransmission/crypto-utils-openssl.c:343: error: undefined reference to 'DH_get0_key'
```
This issue might have been introduced with 22bde65
Any idea how to fix?

**Comment by mikedld** [comment]
Sorry, I missed those when cherry-picking to 2.93. See if applying changes from #284 fixes it.

**Comment by thoradia** [comment]
Thanks, this fixes:
```
diff -Naur transmission-2.93/libtransmission/crypto-utils-openssl.c transmission-2.93.libressl/libtransmission/crypto-utils-openssl.c
--- transmission-2.93/libtransmission/crypto-utils-openssl.c	2018-01-23 20:17:43.000000000 +0100
+++ transmission-2.93.libressl/libtransmission/crypto-utils-openssl.c	2018-01-25 09:24:16.023700941 +0100
@@ -147,7 +147,7 @@
 ****
 ***/
 
-#if OPENSSL_VERSION_NUMBER < 0x0090802fL
+#if OPENSSL_VERSION_NUMBER < 0x0090802fL || defined(LIBRESSL_VERSION_NUMBER)
 
 static EVP_CIPHER_CTX *
 openssl_evp_cipher_context_new (void)
@@ -230,7 +230,7 @@
 ****
 ***/
 
-#if OPENSSL_VERSION_NUMBER < 0x10100000
+#if OPENSSL_VERSION_NUMBER < 0x10100000 || defined(LIBRESSL_VERSION_NUMBER)
 static inline int
 DH_set0_pqg (DH     * dh,
              BIGNUM * p,
```

**Comment by mikedld** [comment]
Closing in preparation for 2.94.
