### PR TITLE
Update libutp to 3.4+ (TRAC-5888)

### LINKED ISSUE #2996: consider updating libutp dependency to 2b364cb
Libutp is 12 years old. May 2018 is the most recent, and is surely better than using a 12 year old version. https://github.com/bittorrent/libutp.

@ckerr @mikedld @livings124 I downloaded the latest version and tried to build it for Transmission by altering the current cmakefile. A number of files have changed name, and i've included the alterations to the current makefile, and had my fingers crossed that i was doing the right thing.

These file names no longer exist:

1. utp.cpp
2. utypes.h

cmakefile changes i made are utp_api.cpp and utp_types.h:

"include_directories(.)

add_library(${PROJECT_NAME} STATIC
    utp_api.cpp
    utp_utils.cpp
    ${${PROJECT_NAME}_ADD_SOURCES}
)

install(TARGETS ${PROJECT_NAME} DESTINATION lib)
install(FILES utp.h utp_types.h DESTINATION include/libutp)"

Here's the output during the build process:

```
1 warning generated.
[ 23%] Building CXX object libtransmission/CMakeFiles/transmission.dir/natpmp.cc.o
[ 23%] Building CXX object libtransmission/CMakeFiles/transmission.dir/net.cc.o
/Users/gary/Documents/GitHub/transmission/libtransmission/net.cc:437:42: error: use of undeclared identifier 'UTP_Create'
        struct UTPSocket* const socket = UTP_Create(tr_utpSendTo, session, (struct sockaddr*)&ss, sslen);
                                         ^
/Users/gary/Documents/GitHub/transmission/libtransmission/net.cc:461:9: error: use of undeclared identifier 'UTP_Close'
        UTP_Close(socket.handle.utp);
        ^
2 errors generated.
make[2]: *** [libtransmission/CMakeFiles/transmission.dir/net.cc.o] Error 1
make[1]: *** [libtransmission/CMakeFiles/transmission.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by ckerr**
Fixes #2996.

CC @mikedld 

I think it might make sense to merge this into `main` to get some wider testing?

### CODE REVIEW

**Comment by carandraug** [comment]
This causes a failure to build on my system (gcc 8.3.0 on Debian 10):

```
[ 22%] Building CXX object libtransmission/CMakeFiles/transmission.dir/net.cc.o
warning: unknown warning option '-Wduplicated-cond'; did you mean '-Wduplicate-enum'? [clang-diagnostic-unknown-warning-option]
warning: unknown warning option '-Wint-in-bool-context'; did you mean '-Wgnu-include-next'? [clang-diagnostic-unknown-warning-option]
warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [clang-diagnostic-unknown-warning-option]
warning: unknown warning option '-Wrestrict' [clang-diagnostic-unknown-warning-option]
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [clang-diagnostic-unknown-warning-option]
/home/carandraug/src/external/transmission/libtransmission/net.cc:408:30: error: use of undeclared identifier 'utp_create_socket' [clang-diagnostic-error]
        auto* const socket = utp_create_socket(session->utp_context);
                             ^
/home/carandraug/src/external/transmission/libtransmission/net.cc:439:9: error: use of undeclared identifier 'utp_set_userdata' [clang-diagnostic-error]
        utp_set_userdata(socket.handle.utp, nullptr);
        ^
/home/carandraug/src/external/transmission/libtransmission/net.cc:440:9: error: use of undeclared identifier 'utp_close'; did you mean 'pclose'? [clang-diagnostic-error]
        utp_close(socket.handle.utp);
        ^~~~~~~~~~
        pclose
/usr/include/stdio.h:812:12: note: 'pclose' declared here
extern int pclose (FILE *__stream);
           ^
/home/carandraug/src/external/transmission/libtransmission/net.cc:440:19: error: cannot initialize a parameter of type 'FILE *' (aka '_IO_FILE *') with an lvalue of type 'struct UTPSocket *' [clang-diagnostic-error]
        utp_close(socket.handle.utp);
                  ^
/usr/include/stdio.h:812:26: note: passing argument to parameter '__stream' here
extern int pclose (FILE *__stream);
                         ^
12618 warnings and 4 errors generated.
Error while processing /home/carandraug/src/external/transmission/libtransmission/net.cc.
```

**Comment by mikedld** [comment]
Please try a clean build.

**Comment by carandraug** [comment]
Apologies for the noise. I'm not much used to keeping dependencies as submodules. Fixed after updating the submodules.
