### ISSUE TITLE
Failed to compile on GCC 12.2.0

### ISSUE THREAD

**Issue by trippleflux** [transmission/transmission#3948]
### What is the issue?

I am getting the following when trying to compile for OpenWRT target-arm_cortex-a15+neon-vfpv4_musl_eabi with GCC 12.2.0 on x86_64 : 
```
../libtransmission/trevent.cc: In function 'void {anonymous}::tr_evthread_init_helpers::initEvthreadsOnce()':
../libtransmission/trevent.cc:119:5: error: 'evthread_lock_callbacks' was not declared in this scope
  119 |     evthread_lock_callbacks constexpr LockCbs{
      |     ^~~~~~~~~~~~~~~~~~~~~~~
../libtransmission/trevent.cc:122:34: error: 'LockCbs' was not declared in this scope
  122 |     evthread_set_lock_callbacks(&LockCbs);
      |                                  ^~~~~~~
../libtransmission/trevent.cc:122:5: error: 'evthread_set_lock_callbacks' was not declared in this scope; did you mean 'event_set_log_callback'?
  122 |     evthread_set_lock_callbacks(&LockCbs);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     event_set_log_callback
../libtransmission/trevent.cc:124:5: error: 'evthread_condition_callbacks' was not declared in this scope
  124 |     evthread_condition_callbacks constexpr CondCbs{ EVTHREAD_CONDITION_API_VERSION,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libtransmission/trevent.cc:129:39: error: 'CondCbs' was not declared in this scope
  129 |     evthread_set_condition_callbacks(&CondCbs);
      |                                       ^~~~~~~
../libtransmission/trevent.cc:129:5: error: 'evthread_set_condition_callbacks' was not declared in this scope
  129 |     evthread_set_condition_callbacks(&CondCbs);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libtransmission/trevent.cc:131:5: error: 'evthread_set_id_callback' was not declared in this scope; did you mean 'event_set_log_callback'?
  131 |     evthread_set_id_callback(thread_current_id);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
      |     event_set_log_callback
../libtransmission/trevent.cc: At global scope:
../libtransmission/trevent.cc:108:15: warning: 'long unsigned int {anonymous}::tr_evthread_init_helpers::thread_current_id()' defined but not used [-Wunused-function]
  108 | unsigned long thread_current_id()
      |               ^~~~~~~~~~~~~~~~~
../libtransmission/trevent.cc:93:5: warning: 'int {anonymous}::tr_evthread_init_helpers::cond_wait(void*, void*, const timeval*)' defined but not used [-Wunused-function]
   93 | int cond_wait(void* vcond, void* vlock, struct timeval const* tv)
      |     ^~~~~~~~~
../libtransmission/trevent.cc:79:5: warning: 'int {anonymous}::tr_evthread_init_helpers::cond_signal(void*, int)' defined but not used [-Wunused-function]
   79 | int cond_signal(void* vcond, int broadcast)
      |     ^~~~~~~~~~~
../libtransmission/trevent.cc:74:6: warning: 'void {anonymous}::tr_evthread_init_helpers::cond_free(void*)' defined but not used [-Wunused-function]
   74 | void cond_free(void* vcond)
      |      ^~~~~~~~~
../libtransmission/trevent.cc:69:7: warning: 'void* {anonymous}::tr_evthread_init_helpers::cond_alloc(unsigned int)' defined but not used [-Wunused-function]
   69 | void* cond_alloc(unsigned /*condflags*/)
      |       ^~~~~~~~~~
../libtransmission/trevent.cc:63:5: warning: 'int {anonymous}::tr_evthread_init_helpers::lock_unlock(unsigned int, void*)' defined but not used [-Wunused-function]
   63 | int lock_unlock(unsigned /*mode*/, void* vlock)
      |     ^~~~~~~~~~~
../libtransmission/trevent.cc:51:5: warning: 'int {anonymous}::tr_evthread_init_helpers::lock_lock(unsigned int, void*)' defined but not used [-Wunused-function]
   51 | int lock_lock(unsigned mode, void* vlock)
      |     ^~~~~~~~~
../libtransmission/trevent.cc:46:6: warning: 'void {anonymous}::tr_evthread_init_helpers::lock_free(void*, unsigned int)' defined but not used [-Wunused-function]
   46 | void lock_free(void* vlock, unsigned /*locktype*/)
      |      ^~~~~~~~~
../libtransmission/trevent.cc:41:7: warning: 'void* {anonymous}::tr_evthread_init_helpers::lock_alloc(unsigned int)' defined but not used [-Wunused-function]
   41 | void* lock_alloc(unsigned /*locktype*/)
      |       ^~~~~~~~~~
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

latest git vanilla

**Comment by trippleflux** [comment]
Closed as invalid because forgot to add +libevent2-core +libevent2-extra +libevent2-openssl +libevent2-pthreads to the transmission OpenWrt package dependencies.
