### ISSUE TITLE
4.1.0 beta 1 on macOS 15.2: IPv6 error

### ISSUE THREAD

**Issue by Kurville** [transmission/transmission#7307]
### What is the issue?

The latest beta seems to insist on using IPv6 even though noting in my network can provide such an address: numerous messages in the debugging window points to that problem and Transmission can't connect to any peers. I've gone back to 4.0.6: no IPv6 error message and instant connection to peers.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0 beta 1

**Comment by tearfur** [comment]
What are the exact messages you are seeing?

**Comment by Kurville** [comment]
I should add that I'm using a VPN, so it's probably also a factor.

Startup messages with 4.1.0b1 :

> 2024-12-17 16:45:26 +0000 cache.cc:118 [Débogage] cache.cc:118: Maximum cache size set to 4 Mo (244 blocks)
2024-12-17 16:45:26 +0000 ip-cache.cc:276 [Débogage] ip-cache.cc:276: Successfully updated source IPv4 address to 10.5.0.2
2024-12-17 16:45:26 +0000 ip-cache.cc:283 [Débogage] ip-cache.cc:283: Couldn't obtain source IPv6 address
2024-12-17 16:45:26 +0000 net.cc:362 [Débogage] net.cc:362: Bound socket 6 to port 59068 on 0.0.0.0
2024-12-17 16:45:26 +0000 session.cc:408 [Renseignements] session.cc:408: Listening to incoming peer connections on 0.0.0.0:59068
2024-12-17 16:45:26 +0000 net.cc:362 [Débogage] net.cc:362: Bound socket 7 to port 59068 on ::
2024-12-17 16:45:26 +0000 session.cc:408 [Renseignements] session.cc:408: Listening to incoming peer connections on [::]:59068
2024-12-17 16:45:26 +0000 port-forwarding-natpmp.cc:42 [Débogage] port-forwarding-natpmp.cc:42: initnatpmp succeeded (0)
2024-12-17 16:45:26 +0000 port-forwarding-natpmp.cc:42 [Débogage] port-forwarding-natpmp.cc:42: sendpublicaddressrequest succeeded (2)
2024-12-17 16:45:26 +0000 port-forwarding.cc:219 [Renseignements] port-forwarding.cc:219: State changed from 'Not forwarded' to 'Starting'
2024-12-17 16:45:26 +0000 tr-udp.cc:200 [Renseignements] tr-udp.cc:200: Bound UDP IPv4 address 0.0.0.0:59068
2024-12-17 16:45:26 +0000 tr-udp.cc:245 [Renseignements] tr-udp.cc:245: Bound UDP IPv6 address [::]:59068
2024-12-17 16:45:26 +0000 tr-dht.cc:140 [Débogage] tr-dht.cc:140: Starting DHT on port 59068
2024-12-17 16:45:26 +0000 rpc-server.cc:833 [Débogage] rpc-server.cc:833: setting password-enabled to 'false'
2024-12-17 16:45:26 +0000 rpc-server.cc:761 [Renseignements] rpc-server.cc:761: Added '127.0.0.1' to host whitelist
2024-12-17 16:45:26 +0000 rpc-server.cc:761 [Renseignements] rpc-server.cc:761: Added '::1' to host whitelist
2024-12-17 16:45:26 +0000 rpc-server.cc:820 [Débogage] rpc-server.cc:820: setting our username to 'admin'
2024-12-17 16:45:26 +0000 rpc-server.cc:827 [Débogage] rpc-server.cc:827: setting our salted password to '{c242fab085575df0c5577b1980d1d112ac793b12GfRhHgeh'
2024-12-17 16:45:26 +0000 rpc-server.cc:910 [Renseignements] rpc-server.cc:910: Serving RPC and Web requests from '/Applications/Transmission.app/Contents/Resources/public_html'
2024-12-17 16:45:26 +0000 rpc-server.cc:761 [Renseignements] rpc-server.cc:761: Added '127.0.0.1' to host whitelist
2024-12-17 16:45:27 +0000 ip-cache.cc:316 [Débogage] ip-cache.cc:316: Successfully updated global IPv4 address to 185.199.101.254 using https://ip4.transmissionbt.com/
2024-12-17 16:45:34 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:45:34 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:45:43 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:45:43 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:45:51 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:45:51 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:45:56 +0000 ip-cache.cc:283 [Débogage] ip-cache.cc:283: Couldn't obtain source IPv6 address
2024-12-17 16:45:59 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:45:59 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:46:08 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:46:08 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:46:16 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:46:16 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:46:24 +0000 port-forwarding-upnp.cc:280 [Débogage] port-forwarding-upnp.cc:280: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:46:24 +0000 port-forwarding-upnp.cc:281 [Débogage] port-forwarding-upnp.cc:281: If your router supports UPnP, please make sure UPnP is enabled!
2024-12-17 16:46:26 +0000 ip-cache.cc:283 [Débogage] ip-cache.cc:283: Couldn't obtain source IPv6 address


Compared to startup messages with 4.0.6 :

> 2024-12-17 16:44:08 +0000 session.cc:646 [Renseignements] session.cc:646: Transmission version 4.0.6 (38c164933e) starting
2024-12-17 16:44:08 +0000 cache.cc:123 [Débogage] cache.cc:123: Maximum cache size set to 4.00 Mo (244 blocks)
2024-12-17 16:44:08 +0000 net.cc:324 [Débogage] net.cc:324: Bound socket 6 to port 57218 on 0.0.0.0
2024-12-17 16:44:08 +0000 session.cc:405 [Renseignements] session.cc:405: Listening to incoming peer connections on [0.0.0.0]:57218
2024-12-17 16:44:08 +0000 net.cc:324 [Débogage] net.cc:324: Bound socket 7 to port 57218 on ::
2024-12-17 16:44:08 +0000 session.cc:405 [Renseignements] session.cc:405: Listening to incoming peer connections on [::]:57218
2024-12-17 16:44:08 +0000 port-forwarding-natpmp.cc:38 [Débogage] port-forwarding-natpmp.cc:38: initnatpmp succeeded (0)
2024-12-17 16:44:08 +0000 port-forwarding-natpmp.cc:38 [Débogage] port-forwarding-natpmp.cc:38: sendpublicaddressrequest succeeded (2)
2024-12-17 16:44:08 +0000 port-forwarding.cc:218 [Renseignements] port-forwarding.cc:218: State changed from 'Not forwarded' to 'Starting'
2024-12-17 16:44:08 +0000 tr-udp.cc:168 [Renseignements] tr-udp.cc:168: Bound UDP IPv4 address [0.0.0.0]:57218
2024-12-17 16:44:08 +0000 tr-udp.cc:202 [Renseignements] tr-udp.cc:202: Bound UDP IPv6 address [::]:57218
2024-12-17 16:44:08 +0000 tr-dht.cc:139 [Débogage] tr-dht.cc:139: Starting DHT on port 57218
2024-12-17 16:44:08 +0000 rpc-server.cc:836 [Débogage] rpc-server.cc:836: setting password-enabled to 'false'
2024-12-17 16:44:08 +0000 rpc-server.cc:763 [Renseignements] rpc-server.cc:763: Added '127.0.0.1' to host whitelist
2024-12-17 16:44:08 +0000 rpc-server.cc:763 [Renseignements] rpc-server.cc:763: Added '::1' to host whitelist
2024-12-17 16:44:08 +0000 rpc-server.cc:822 [Débogage] rpc-server.cc:822: setting our username to 'admin'
2024-12-17 16:44:08 +0000 rpc-server.cc:830 [Débogage] rpc-server.cc:830: setting our salted password to '{46f05f699a388db1b12ec7d1de7b0b978140c66aSTEFPSpI'
2024-12-17 16:44:08 +0000 rpc-server.cc:923 [Renseignements] rpc-server.cc:923: Serving RPC and Web requests from '/Applications/Transmission.app/Contents/Resources/public_html'
2024-12-17 16:44:08 +0000 rpc-server.cc:763 [Renseignements] rpc-server.cc:763: Added '127.0.0.1' to host whitelist
2024-12-17 16:44:16 +0000 port-forwarding-upnp.cc:290 [Débogage] port-forwarding-upnp.cc:290: UPNP_GetValidIGD failed: Resource temporarily unavailable (35)
2024-12-17 16:44:16 +0000 port-forwarding-upnp.cc:291 [Débogage] port-forwarding-upnp.cc:291: If your router supports UPnP, please make sure UPnP is enabled!

**Comment by tearfur** [comment]
Oh, that's just a debug message. You can safely ignore it.

**Comment by Kurville** [comment]
OK, but using a VPN, no peers...

**Comment by tearfur** [comment]
Are you on trackers that limit your client version? `4.1.0-beta1` probably isn't whitelisted anywhere.

Fyi, the new debug messages you are seeing in `4.1.0-beta1` are from a new feature that periodically probes for your source address and global unicast address. It shouldn't have anything to do with you not getting any peers.I see in the logs that it found your nordvpn public address.

On both versions you are bound to `0.0.0.0` and `::`, natpmp succeeeded (port forwarded). If I didn't miss anything, you should *theoretically* be able to connect to peers just fine. And I see that our IP checking service even found your nordvpn address and returned it to your `4.1.0-beta1` client, so you should be able to connect to trackers.

**Comment by Kurville** [comment]
Same trackers (and I guess roughly the same peers):

- no VPN, 4.1.0-beta 1 connects to peers (although it takes longer than 4.0.6)
- with VPN, 4.1.0-beta 1 doesn't connect to peers at all (but I guess it could be a problem with trackers).

**Comment by tyler-nguyen** [comment]
Something is wrong with this change https://github.com/transmission/transmission/pull/7027. Reversing it (checking out from tag 4.1.0-beta1) and building from source fix the issue.

**Comment by Kurville** [comment]
Using a VPN, 4.1.0-beta.1 still doesn't connect to peers. NordVPN and macOS 15.3.2.

**Comment by tearfur** [comment]
I'm not sure how I can help you any further. I don't have a Mac to test and I don't use NordVPN either.

Let's hope that someone else will figure something out.

**Comment by tgt** [comment]
I hope this isn't a red herring, as I don't actually know what the code is doing, but after using git bisect I also found that 7e4b4f10a1f90885c0bebb168eedffe153f1cf53 was responsible for Transmission not working on macOS with a VPN. With a bit of digging, I found that commenting out the following lines fixed the issue.

https://github.com/transmission/transmission/blob/ac5c9e082da257e102eb4ff18f2e433976a585d1/libtransmission/peer-io.cc#L573-L580

Perhaps that's helpful?

Please let me know if there's any way I can help.

**Comment by tgt** [comment]
I just downloaded 4.1.0 and I'm still seeing issues when connected to a VPN. It's not as bad as it was when I commented on this issue, when I couldn't connect to any peers, but things aren't working properly. Performance is worse than with 4.0.6 whether or not I'm connected to a VPN.

I downloaded Fedora-Workstation-Live-x86_64-43 using 4.0.6 and 4.1.0 with and without a VPN a couple of times. The speeds were consistent across those runs as show below:

4.1.0 + VPN: 3 MB/s
4.1.0 (no VPN): 20 MB/s
4.0.6 + VPN: 35 MB/s
4.0.6 (no VPN): 70 MB/s

The 4.1.0 logs contain lots of mentions of `setting <ip> is_disconnecting_ flag because we got [(57) Socket is not connected]`, which is the same thing I saw with the older beta.

I've attached the logs for the above runs.

I can build Transmission from source and see whether the “workaround” I mentioned in my previous comments resolves the issue if you'd like.

[4.0.6-no-vpn.txt](https://github.com/user-attachments/files/24912808/4.0.6-no-vpn.txt)
[4.0.6-vpn.txt](https://github.com/user-attachments/files/24912806/4.0.6-vpn.txt)
[4.1.0-no-vpn.txt](https://github.com/user-attachments/files/24912807/4.1.0-no-vpn.txt)
[4.1.0-vpn.txt](https://github.com/user-attachments/files/24912805/4.1.0-vpn.txt)

**Comment by Kurville** [comment]
I see there's an update for 4.1.0 that I haven't tested yet, but a thing I observed with 4.1.0 beta 5:
although much better than early beta 1 and beta 2, 4.1.0 beta 5 was still outperformed by 4.0.6 in terms of number of peers connected and maybe also download speed, VPN or not.

I will start using 4.1.0 and see if performance is better.

**Comment by tgt** [comment]
I tried using `git bisect`, but I get build errors on lots of older commits (error: use of undeclared identifier 'ngettext') and varying issues (not connecting to peers, connecting to a few, poor performance) on those that build, which makes determining which are good or bad difficult. I can have another go if you can't find a way to track down the issue, but hopefully someone with a Mac and familiarity with the codebase can have a look.

The workarounds I mentioned last time don't seem to work, so either the issue is different or it just no longer delays the right thing in just the right way.

**Comment by Kurville** [comment]
Updated to 4.1.1 today. The problems I was having with 4.1.0 (all the betas and release) seem to be solved. Looking at the 4.1.1 release notes I don't know what did the trick, but, in any case, it looks like I'm finally leaving 4.0.6 behind.

Cheers!

**Comment by tgt** [comment]
The performance issues I mentioned in https://github.com/transmission/transmission/issues/7307#issuecomment-3811574803 are still present with 4.1.1, but perhaps that's better tracked by #8305. If the logs there look useful for @tearfur or @ckerr, I could copy my comment across to the other issue.

**Comment by Kurville** [comment]
Hum, OK. My home internet is not that fast, so it's hard to judge a speed loss, but, back at work on Monday, I'll have better conditions to evaluate speed.

That being said, my biggest problem was peer connection and that seems to be solved.

**Comment by tyler-nguyen** [comment]
I think this change https://github.com/transmission/transmission/pull/8454 did the trick. It changed the lines mentioned in https://github.com/transmission/transmission/issues/7307#issuecomment-2724318346.

**Comment by Kurville** [comment]
OK, informal comparaison between 4.1.1 and 4.06 on macOS 26.3 using a VPN.

4.1.1 is way better than than any version on 4.1.0, but 4.0.6 still performs better regarding number of peers connected, download speed, and ability to finish at the very end. It can hang at 99.99 %. I quit 4.1.1 and re-open in 4.0.6, it will rapidly finish those hanged torrents. All this seems to be quite elusive, but I guess the question to be asked is what was fundamentally changed between 4.0.6 and all subsequents versions that controls the aforementioned aspects of Transmission.

**Comment by tyler-nguyen** [comment]
Actually https://github.com/transmission/transmission/pull/8454 doesn't fix the problem.

There is this bug https://github.com/transmission/transmission/issues/8643 that makes Transmission to use uTP even when uTP is disabled. Using the latest code on branch 4.1.x, which contains the fix https://github.com/transmission/transmission/pull/8658, no connection can be made if uTP is disabled. This might also explain the speed problem, because downloading with TCP is faster than with uTP.

I don't understand what this code actually does, or why it causes the problem for TCP. But everything works well if I replace this in peer-io.cc

https://github.com/transmission/transmission/blob/79c7e70958df1a6540ed4a8f83e95cbd9a4e3e73/libtransmission/peer-io.cc#L108-L115

with this (to write only for uTP and skip for TCP)

```C++
io->flush_outbuf_trigger_->set_callback(
  [weak = io->weak_from_this()]
  {
      if (auto const ptr = weak.lock())
      {
          if (ptr->is_utp())
          {
              ptr->try_write(SIZE_MAX);
          }
      }
  });
```

If this is truly not needed for TCP, the above can even be a proper fix.

**Comment by tearfur** [comment]
@tyler-nguyen Before anything, I'm slightly lost on the topic. Are you saying making your modification fixes the speed issue, or are you saying it also fixes not connecting to peers?

The idea of the code snippet you quoted is to flush the outgoing buffer as soon as new data was pushed to it. It's not needed per se, but without it, outgoing messages will be flushed in batches every 0.5 seconds.

In the BT protocol, you will not download any data if you don't send requests to peers. If these requests are sent out in batches, they will most probably be delayed, and this slows down your download. This starts getting obvious beyond 1Gbps in my empirical testing.

Whether you're using TCP or uTP shouldn't matter in this context, so if TCP/uTP did matter, then there's a bug somewhere.

**Comment by tgt** [comment]
@tearfur It fixes not connecting to peers for me, but so does just commenting it out as I reported in https://github.com/transmission/transmission/issues/7307#issuecomment-2724318346. (It’s now necessary to comment out just lines 111-114 since commenting out the set_callback call itself causes Transmission to crash when flush_outbuf_soon is called.)

My current experience is that 4.0.6 connects to peers and is fast; 4.1.1 connects to peers, but is fairly slow; and main doesn't connect to peers at all. Some change between 4.1.1 and main has caused the inability to connect to peers that I experienced with the 4.1.0 betas to return.

I use Little Snitch, a firewall, and if I delay allowing it to let through Transmission’s traffic for a moment, Transmission is able to connect to some peers. If I disable it, so that any connections can go through without approval, Transmission is unable to connect to any. Some delay seems to allow something to be established properly, as I mentioned in the above issue.

Is there anything you can point me towards so I can help debug this?

Are there any useful logs I can provide? I attached some in
https://github.com/transmission/transmission/issues/7307#issuecomment-3811574803, but the suspicious looking thing I noted in them is no longer being printed. In fact, the logs when Transmission is not connecting to peers and when it is (with the above-mentioned lines commented out) look pretty much the same now.

(If there's nothing useful I can do or provide, or if my comments are unhelpful, please let me know.)

**Comment by tyler-nguyen** [comment]
@tearfur I mean it fixes the connection issue for TCP.

Am I correct to think that this code will achieve the same thing? Or calling `set_enabled` like that doesn't actually do anything? TCP connections work with this code.

```C++
    io->flush_outbuf_trigger_->set_callback(
        [weak = io->weak_from_this()]
        {
            if (auto const ptr = weak.lock())
            {
                if (ptr->is_utp()) {
                    ptr->try_write(SIZE_MAX);
                } else {
                    ptr->set_enabled(tr_direction::Up, true);
                }
            }
        });
```

I see that only TCP uses `event_write_cb`, and `try_write` also calls `set_enabled` to enable further writes or retry errors.

**Comment by tearfur** [comment]
@tgt 

> I use Little Snitch, a firewall, and if I delay allowing it to let through Transmission’s traffic for a moment, Transmission is able to connect to some peers.

Hmm, you just gave me an idea. Can you try out this patch? If this works, try changing `3000` to `128` and see if it also works.

```diff
diff --git a/libtransmission/peer-io.cc b/libtransmission/peer-io.cc
index 037c2f6d8..85f67d216 100644
--- a/libtransmission/peer-io.cc
+++ b/libtransmission/peer-io.cc
@@ -111,7 +111,10 @@ std::shared_ptr<tr_peerIo> tr_peerIo::create(
         {
             if (auto const ptr = weak.lock())
             {
-                ptr->try_write(SIZE_MAX);
+                if (ptr->outbuf_.size() >= 3000)
+                {
+                    ptr->try_write(SIZE_MAX);
+                }
             }
         });
     tr_logAddTraceIo(io, fmt::format("bandwidth is {}; its parent is {}", fmt::ptr(&io->bandwidth()), fmt::ptr(parent)));
```

@tyler-nguyen No, it does not do the same thing. `set_enabled()` does enable writes, but it does not flush the out buffer immediately.

**Comment by tgt** [comment]
@tearfur Yes, that also seems to fix connecting to peers and it still works with 128. In case it's useful, I tried reducing the number and Transmission stops connecting to peers at 68.

Download speed is still significantly worse than 4.0.6 as described in https://github.com/transmission/transmission/issues/7307#issuecomment-3811574803, but main seems to have improved since 4.1.0.

main + VPN: 15 MB/s
main (no VPN): 25 MB/s
4.0.6 + VPN: 35 MB/s
4.0.6 (no VPN): 70 MB/s

**Comment by tearfur** [comment]
That's a huge hint. I wonder what's the significance of 68 bytes in our context? Could it be a variant of Nagle? Or did our small packets got flagged by the ISP or VPN provider?

Maybe the VPN provider will have an idea?

In any case, I think I will go with 128 for now. It's a good size for the cache, it gives a reasonably leeway from 68, and this size is field tested by libtorrent-rasterbar.

As for the speed drop, I still have no idea. I'm seeing quite the opposite on my end. Just to clarify, you tested on `main` without any patches, right?

**Comment by tgt** [comment]
I've not been using a VPN for testing this (although I've verified that it still works when connected). I've tried with and without Apple’s Private Relay and it makes no difference. I've also tried it with both my fibre connection and tethering and that also makes no difference. Perhaps it's a macOS thing? If you have a suggestion of how to investigate and believe it's worth doing so, I'm happy to have a look. Since 128 seems to work, I suspect there are more important issues.

Yeah, It's main plus the `if (ptr->outbuf_.size() >= 128) { ... }` patch.

I managed to (mostly) automate `git bisect` and it found a4cc98b to be the culprit. It's consistently ~25MB/s whilst the previous commit (536fe4a) is consistently ~70MB/s. Any idea why that might be?

Edit: I hadn't thought about it since my download speed didn't seem limited, but that commit made me look at my bandwidth limits. I didn't have one for download, but I did have the upload limit set to 32KB/s. If I disable the upload limit, the issue goes away. Increasing the upload bandwidth limit also solves the problem. Above 92KB/s it's the same is if there's no limit. The limit was active at 32KB/s in every test whilst bisecting.

Edit 2: An upload limit of 0KB/s also fixes the issue. Small limits (1KB/s, for example) result in far fewer peers connecting and download speeds to be greatly reduced.

**Comment by tearfur** [comment]
Oh man, a new wrench has been thrown into the works.

So if it's `main` without the patch and unlimited bandwidth limits, how's the download speed looking?

> I managed to (mostly) automate `git bisect` and it found [a4cc98b](https://github.com/transmission/transmission/commit/a4cc98b92c80c08abd3b49d2479ef99130f8cea2) to be the culprit.

This might explain why uTP is not affected, because later in bae63e4cfc03398b53ea69c34d564ee554ea2c5c I reverted the logic back to pre- a4cc98b92c80c08abd3b49d2479ef99130f8cea2 just for uTP.

**Comment by tgt** [comment]
`main` without the patch and with unlimited bandwidth doesn't connect to any peers.

**Comment by tearfur** [comment]
Ok so not connecting to peers and slow download speeds are separate. That's good.

To summarise:
- Cause of not connecting to peers: Sending TCP segments with payload size <= 68 bytes
- Cause of slow download: Upload speed limit too low

@tyler-nguyen Anything to add from you? Are these the same problems you've been facing?

**Comment by tearfur** [comment]
Some more context:

> An upload limit of 0KB/s also fixes the issue.

In the current code, 0 Kb/s speed limit is the same as unlimited. 

> Small limits (1KB/s, for example) result in far fewer peers connecting and download speeds to be greatly reduced.

Each BT block request is 136 bytes in size, and they take up upload bandwidth. In perfect conditions with upload limit 1 Kb/s, i.e. BT block requests are the only outgoing traffic + peers don't choke/disconnect you, the peak download speed you can achieve is `1000 / 136 = 7.35 blocks = 117.65 KiB/s = 120.47 Kb/s`.

In practice, the speed is likely lower because, this 1 Kb/s will be spread among the connected peers, BT block requests are not the only outgoing traffic, and most peers will either choke you or disconnect you for low activity.

**Comment by tgt** [comment]
I'd have expected an upload limit of 0KB/s to prevent uploading (beyond requests for blocks and other things necessary to downloading), but fair enough and good to know.

If I use 536fe4a (the commit prior to the one that breaks download speed) and set the upload limit to 1KB/s, I still get download speeds exceeding 70MB/s.

**Comment by tearfur** [comment]
> I'd have expected an upload limit of 0KB/s to prevent uploading (beyond requests for blocks and other things necessary to downloading)

I don't think the current behaviour was a conscious decision, but I'm leaning to keep it that way because prevent uploading essentially cripples the client (cannot download, cannot upload), and that makes even less sense.

> If I use [536fe4a](https://github.com/transmission/transmission/commit/536fe4a6e14b26dda0feac87559ac54af0fddb1b) (the commit prior to the one that breaks download speed) and set the upload limit to 1KB/s, I still get download speeds exceeding 70MB/s.

That's because before the "breaking commit", the speed limits were acting on the "piece speed", i.e. the speed only counted torrent data and excluded all protocol overheads (including the BT protocol). But because torrent data's atomic unit is blocks of 16 KiB, combined with the way our speed limiters work, the speed limiter couldn't keep the speeds below 16 KiB/s.

The "breaking commit" changed the speed limiter to use the "raw speed", which is all BT traffic including the BT protocol overhead, so that the speed limiter works under 16 KiB/s as well. But the side effect is you risk accidentally choking the BT protocol if you set the speed limits too low (empirically it starts to get risky under 100 Kb/s, as you also observed). I made a conscious decision to take this tradeoff.

**Comment by tgt** [comment]
Thank you for the explanation. It makes sense and is what I suspected just after sending my last message. However, it isn't the behaviour I expected as a user.

I wonder if any of the other reports about slow speeds (https://github.com/transmission/transmission/issues/8738, https://github.com/transmission/transmission/issues/8692, https://github.com/transmission/transmission/issues/8680, https://github.com/transmission/transmission/issues/8305, https://github.com/transmission/transmission/issues/8308) are due to this.

**Comment by tyler-nguyen** [comment]
> Ok so not connecting to peers and slow download speeds are separate. That's good.
> 
> To summarise:
> 
> * Cause of not connecting to peers: Sending TCP segments with payload size <= 68 bytes
> * Cause of slow download: Upload speed limit too low
> 
> [@tyler-nguyen](https://github.com/tyler-nguyen) Anything to add from you? Are these the same problems you've been facing?

@tearfur

I only have the peer connecting issue, which is fixed by setting TCP segment to 128 like you're planning to do.

I don't set any bandwidth limit (upload or download). That could explain why I don't have the download speed problem.
