### PR TITLE
bumping libdeflate/small/utfcpp to newer versions

### PR DESCRIPTION
**Pull request by Coeur**
- bumping libdeflate from 1.18 to 1.19
- bumping small from 0.2.0 to 0.2.1
- bumping utfcpp from 3.2.1 to 4.0.5
- <s>using original repositories when there are zero modifications necessary for Transmission, allowing easier updates of those dependencies, since almost nobody can make pull requests to the Transmission forks.</s>

### CODE REVIEW

**Comment by tearfur** [comment]
I'm going to wait for Charles to give his opinion first. He has his reasons for using forks after all https://github.com/transmission/transmission/pull/6138#discussion_r1367184713.

**Comment by Coeur** [comment]
If there is ever an upstream repo breakage, then we would simply update the link to a fork. But it's causing too much hassle to discover and update the third-party versions when they are gated by our unmaintained fork.

**Comment by Coeur** [comment]
@tearfur there is one for you: the latest small doesn't build with GCC 8.5 on NetBSD/amd64:
https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity/405198?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandchucktcpluginBuild=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true
```
In file included from ../../third-party/small/include/small/map.hpp:11,
                 from ../../libtransmission/announce-list.cc:11:
../../third-party/small/include/small/vector.hpp: In member function 'constexpr small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::iterator small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::erase(small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::const_iterator, small::vector<T, N, Allocator, AllowHeap, SizeType, GrowthFactor>::const_iterator)':
../../third-party/small/include/small/vector.hpp:1090:26: error: 'for_each_n' is not a member of 'std'
                     std::for_each_n(
                          ^~~~~~~~~~
../../third-party/small/include/small/vector.hpp:1090:26: note: suggested alternative: 'for_each'
                     std::for_each_n(
                          ^~~~~~~~~~
                          for_each
Process exited with code 1
```

**Comment by tearfur** [comment]
That's annoying... Right I'll create a PR at upstream.

**Comment by nevack** [comment]
> That's annoying... Right I'll create a PR at upstream.

I wanted to say "Do we really need to support such rather old compilers?", but GCC 8.5.0 is not even 3 years old, and for C/C++ compiler it's like yesterday :smile:

**Review by ckerr — CHANGES_REQUESTED** [review]
For the reasons that @tearfur linked to, I'd prefer to have `transmission/transmission` git dependencies pointing to other `transmission/*` repositories. 

I'm happy to sync any modules.

TBH I don't think this is even a how-many-people-have-permission issue; it would be better if none of us had to do this chore. I'll look to see if there's a way to automate the task.

Other than that, I'm :+1: on the idea of bumping dependencies as long as CI is happy

**Comment by ckerr** [comment]
> TBH I don't think this is even a how-many-people-have-permission issue; it would be better if none of us had to do this chore. I'll look to see if there's a way to automate the task.

Looks like https://github.com/apps/pull might be good

**Comment by tearfur** [comment]
> I'll look to see if there's a way to automate the task.

Oh yes please!

**Comment by Coeur** [comment]
Note that I do not have the privilege to dismiss a review:
Capture d’écran 2024-03-17 à 11 34 03

**Comment by Coeur** [comment]
Ah, the fix for small has landed: https://github.com/alandefreitas/small/pull/44.
Let me re-add `small` update.

**Comment by Coeur** [comment]
> I'm happy to sync any modules.

You'll need to re-sync `small` for this PR, @ckerr.

**Comment by tearfur** [comment]
> Looks like https://github.com/apps/pull might be good

@ckerr Looks promising to me too.

**Comment by ckerr** [comment]
I've installed https://github.com/apps/pull for https://github.com/transmission/fmt as a trial installation. Since upstream fmt gets commits pretty frequently, we can watch our fork and see how it works out.

Doesn't look like there are any configuration options for `apps/pull` e.g. on how often to check, so my _guess_ is it'll be triggered whenever there are upstream commits  :man_shrugging: we'll see

**Review by ckerr — APPROVED** [review]

**Comment by tearfur** [comment]
@Coeur Can you link #6709 to this issue? If I remember correctly, GitHub will automatically close it once you do.
